### ISSUE TITLE
support qXfer packets

### ISSUE THREAD

**Issue by tromey** [luser/rust-gdb-remote-protocol#24]
I think at least `qXfer:exec-file:read` is desirable.  These packets require advertising the feature to gdb.

**Comment by luser** [comment]
We're absolutely going to want `qXfer:features:read` as well to support XML target descriptions. We discussed this elsewhere, but I'd love to have support for common targets baked-in and just something like a `fn target(&self) -> Target` method on `Handler` so that we could transparently support those targets without extra work from users of the crate, and maybe some additional methods on `Handler` to allow arbitrary targets.

**Comment by tromey** [comment]
Duplicate of #8.
Somehow I didn't notice.
